api-version: '1.21'
name: Bullseye
version: '1.0.0'
main: tsd.beye.Bullseye
authors:
  - Peach Tree Studios
folia-supported: true
dependencies:
  server:
    MythicMobs:
      load: BEFORE
      required: false
      join-classpath: true
    ModelEngine:
      load: BEFORE
      required: false
      join-classpath: true
    ModelEngineR4:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    TAB:
      load: BEFORE
      required: false
      join-classpath: true
    WorldEdit:
      load: BEFORE
      required: false
      join-classpath: true
    WorldGuard:
      load: BEFORE
      required: false
      join-classpath: true
    MMOItems:
      load: BEFORE
      required: false
      join-classpath: true
    Nexo:
      load: BEFORE
      required: false
      join-classpath: true
    Oraxen:
      load: BEFORE
      required: false
      join-classpath: true
    ChampionAllies:
      load: BEFORE
      required: false
      join-classpath: true
