name: MythicMobs
author: Lumine
main: io.lumine.mythic.bukkit.MythicBukkit
version: 5.11.2-SNAPSHOT-4a0ae732
api-version: 1.13
folia-supported: true
softdepend:
- Multiverse-Core
- Heroes
- PhatLoots
- Vault
- MagicSpells
- MiniaturePets
- LibsDisguises
- WorldGuard
- Holograms
- HolographicDisplays
- PlaceholderAPI
loadbefore: [Quests]
description: The total solution for all things mob-related.
libraries:
  - net.kyori:adventure-api:4.16.0
  - net.kyori:adventure-platform-bukkit:4.3.2
  - net.kyori:adventure-text-minimessage:4.16.0
  - net.kyori:adventure-text-serializer-gson:4.16.0
commands:
  mythicmobs:
    description: MythicMobs base command
    aliases: [mm]
  mythicmobsmenu:
    description: MythicMobs menu command
    aliases: [mmmenu,mmm]
  spawnmob:
    description: Spawn a mob
    aliases: [spawnmythicmob,mspawn,msummon]
  pins:
    description: Easier command for pins
    aliases: [pin]
  addpin:
    description: quickly adds a pin
permissions:
  mythicmobs.admin:
    description: Gives access to everything!
    default: op
  mythicmobs.reload:
    description: Gives access /mm reload!
    default: op
  mythicmobs.signal:
    description: Gives access /mm signal!
    default: op